### PR TITLE
More visual appeal

### PR DESCRIPTION
**Pull request by salaman**
Made the site more appealing to today's young generation.

### CODE REVIEW

**Comment by RikilD** [comment]
I will need to review this pull request. Please give me 2 to 10 business days. Thank you :-)

**Review by RikilD — CHANGES_REQUESTED** [review]
Please use 3 spaces for indents. Thank you.

**Comment by salaman** [comment]
Fixed

**Review by RikilD — COMMENTED** [review]
Great work! :-D

**Pull request merged**
